FROM node:lts-alpine

WORKDIR /client

COPY . /client

ENV BROWSER=none

# Install dependencies
RUN npm ci

# Build the application
RUN npm run build-storybook

# Expose the port
EXPOSE 8080

# Start the application
ENTRYPOINT ["npx"]
CMD ["http-server", "storybook-static", "-p", "6006"]
