services:
    app:
        container_name: matchworks-client
        image: s3975162/matchworks-client:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VITE_SERVER_URL: ${VITE_SERVER_URL}
        ports:
            - 4173:4173
        environment:
            - VITE_SERVER_URL=${VITE_SERVER_URL}
