services:
    app:
        container_name: matchworks-server
        image: s3975162/matchworks-server:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        environment:
            - CLIENT_URL=${CLIENT_URL}
            - MONGO_URI=${MONGO_URI}
            - SERVER_PORT=8080
            - ACCESS_TOKEN_SECRET=mw_access_token_secret
            - ACCESS_TOKEN_LIFE=30m
            - REFRESH_TOKEN_SECRET=mw_refresh_token_secret
            - REFRESH_TOKEN_LIFE=30d
            - GEMINI_API_KEY=${GEMINI_API_KEY}
